- hosts: localhost
  vars:
    temporary_files_path: /home/{{ initlaptop_user }}/git/init-laptop/
    slack_bin_url: https://downloads.slack-edge.com/linux_releases/slack-desktop-3.3.3-amd64.deb
    initlaptop_user: bpetit
  tasks:
    - name: get vimrc
      get_url: url={{ initlaptop_vimrc_url }} dest={{ item }}
      with_items:
        - "/home/{{ initlaptop_user }}/.vimrc"
        - "/root/.vimrc"
    - name: set vimrc ownership and permissions
      file: path=/home/{{ initlaptop_user }}/.vimrc owner={{ initlaptop_user }} group={{ initlaptop_user }} mode=0640
    - name: install useful packages
      package: name={{ item }} state=present
      with_items:
        - nmap
        - htop
        - ncdu
        - terminator
        - owncloud-client
        - ferm
        - tcpdump
        - wireshark
        - nload
        - mtr-tiny
        - keepassx
        - docker.io
        - docker-compose
        - pidgin
        - pidgin-otr
        - powertop
        - sshpass
        - curl
        - vlc-bin
        - vlc
        - tig
        - vim
    - name: install slack
      get_url:
        url: "{{ slack_bin_url }}"
        dest: "{{ temporary_files_path }}/slack.deb"
    - name: install slack
      apt:
        deb: "{{ temporary_files_path }}/slack.deb"
    - name: ensure known hosts are not hashed
      lineinfile:
        dest: /etc/ssh/ssh_config
        regexp: "^    HashKnownHosts yes"
        line: "    HashKnownHosts no"
        backrefs: yes
    - name: insert autocompletion config in bashrc
      copy: src=files/etc/bash_completion.d/known-hosts dest=/etc/bash_completion.d/known-hosts owner=root group=root mode=0644
