- hosts: localhost
  connection: local
  vars:
    initlaptop_temporary_files_path: "/home/{{ ansible_user_id }}/git/init-laptop/"
    initlaptop_slack_bin_url: "https://downloads.slack-edge.com/linux_releases/slack-desktop-3.3.3-amd64.deb"
    initlaptop_vim_path: "/home/{{ ansible_user_id }}/.vim"
    initlaptop_vim_plug_path: "{{ initlaptop_vim_path }}/autoload"
    initlaptop_vim_plug_url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  tasks:
    - name: configure vim
      include_tasks: vim.yml
    - name: install useful packages
      include_tasks: packages.yml
    - name: ensure known hosts are not hashed
      lineinfile:
        dest: /etc/ssh/ssh_config
        regexp: "^    HashKnownHosts yes"
        line: "    HashKnownHosts no"
        backrefs: yes
      become: true
    - name: build specific bash configuration 
      include_tasks: bash.yml
