- hosts: localhost
  connection: local
  vars:
    initlaptop_temporary_files_path: "/home/{{ ansible_user_id }}/git/init-laptop/"
    initlaptop_slack_bin_url: "https://downloads.slack-edge.com/linux_releases/slack-desktop-3.3.3-amd64.deb"
    initlaptop_vim_path: "/home/{{ ansible_user_id }}/.vim"
    initlaptop_vim_plug_path: "{{ initlaptop_vim_path }}/autoload"
    initlaptop_vim_plug_url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  tasks:
    - name: configure vim
      include_tasks: vim.yml
    - name: install useful packages
      become: true
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - nmap
        - htop
        - ncdu
        - terminator
        - owncloud-client
        - ferm
        - tcpdump
        - wireshark
        - nload
        - mtr-tiny
        - keepassx
        - docker.io
        - docker-compose
        - pidgin
        - pidgin-otr
        - powertop
        - sshpass
        - curl
        - vlc-bin
        - vlc
        - tig
        - vim
        - oathtool
    - name: download slack
      get_url:
        url: "{{ initlaptop_slack_bin_url }}"
        dest: "{{ initlaptop_temporary_files_path }}/slack.deb"
    - name: install slack
      apt:
        deb: "{{ initlaptop_temporary_files_path }}/slack.deb"
    - name: ensure known hosts are not hashed
      lineinfile:
        dest: /etc/ssh/ssh_config
        regexp: "^    HashKnownHosts yes"
        line: "    HashKnownHosts no"
        backrefs: yes
    - name: insert autocompletion config in bashrc
      copy:
        src: "files/etc/bash_completion.d/known-hosts"
        dest: "/etc/bash_completion.d/known-hosts"
        owner: "root"
        group: "root"
        mode: "0644"
